export const modules = [
  {
    id: "home",
    path: "/",
    label: "Inicio",
    icon: "home",
    title: "Vista general",
    description: "Estado de la plataforma y accesos rápidos",
  },
  {
    id: "applications",
    path: "/aplicaciones",
    label: "Aplicaciones",
    icon: "apps",
    title: "Aplicaciones",
    description: "Inventario de servicios que delegan seguridad",
    action: "Registrar aplicación",
  },
  {
    id: "resources",
    path: "/recursos",
    label: "Recursos",
    icon: "route",
    title: "Recursos",
    description: "Endpoints HTTP registrados en el perímetro",
    action: "Registrar recurso",
  },
  {
    id: "roles",
    path: "/roles",
    label: "Roles",
    icon: "key",
    title: "Roles",
    description: "Catálogo de roles y su alcance",
    action: "Definir rol",
  },
  {
    id: "assignments",
    path: "/asignaciones",
    label: "Asignaciones",
    icon: "link",
    title: "Asignaciones",
    description: "Qué rol tiene cada usuario, en qué aplicación",
    action: "Asignar rol",
  },
  {
    id: "profiles",
    path: "/perfiles",
    label: "Perfiles",
    icon: "layers",
    title: "Perfiles",
    description: "Agrupan varios roles para asignarlos de una sola vez",
    action: "Definir perfil",
  },
  {
    id: "profileAssignments",
    path: "/asignaciones-de-perfil",
    label: "Asig. de perfiles",
    icon: "link",
    title: "Asignaciones de perfil",
    description: "Qué perfil tiene cada usuario, en qué aplicación",
    action: "Asignar perfil",
  },
  {
    id: "authorize",
    path: "/autorizacion",
    label: "Probar acceso",
    icon: "bolt",
    title: "",
    description: "",
  },
  {
    id: "tenants",
    path: "/tenants",
    label: "Tenants",
    icon: "tenants",
    title: "Tenants",
    description: "Particiones organizacionales activas",
    action: "Crear tenant",
  },
  {
    id: "users",
    path: "/usuarios",
    label: "Usuarios",
    icon: "users",
    title: "Usuarios",
    description: "Identidades que ya iniciaron sesión",
  },
] as const;
export type ModuleId = (typeof modules)[number]["id"];
